<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Captureing ScreenShot]]>
    </line>
    <line>
      <![CDATA[<a target="blank"href=Mon_Nov_11_16_20_03_IST_2019.jpg>ScreenShot</a>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Basic" duration-ms="1259" started-at="2019-11-11T10:50:02Z" finished-at="2019-11-11T10:50:04Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="1199" started-at="2019-11-11T10:50:02Z" finished-at="2019-11-11T10:50:04Z">
      <class name="com.learn.testcases.BankManagerLoginTest">
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:com.learn.testcases.BankManagerLoginTest@4a883b15]" name="loginAsBankManager" duration-ms="94" started-at="2019-11-11T16:20:02Z" finished-at="2019-11-11T16:20:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [xyz] but found [abc]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [xyz] but found [abc]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.learn.testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Captureing ScreenShot]]>
            </line>
            <line>
              <![CDATA[<a target="blank"href=Mon_Nov_11_16_20_03_IST_2019.jpg>ScreenShot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.learn.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Login Test" duration-ms="11" started-at="2019-11-11T10:50:04Z" finished-at="2019-11-11T10:50:04Z">
      <class name="com.learn.testcases.AddCustomerLoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.learn.testcases.AddCustomerLoginTest@738dc9b]" name="setUp" is-config="true" duration-ms="11841" started-at="2019-11-11T16:19:51Z" finished-at="2019-11-11T16:20:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.learn.testcases.AddCustomerLoginTest@738dc9b]" name="addCustomerTest" duration-ms="0" started-at="2019-11-11T16:20:04Z" data-provider="dp" finished-at="2019-11-11T16:20:04Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Can't invoke method public java.lang.Object[][] com.learn.utilities.TestUtil.getData(java.lang.reflect.Method) on this instance of class com.learn.testcases.AddCustomerLoginTest due to class mismatch]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Can't invoke method public java.lang.Object[][] com.learn.utilities.TestUtil.getData(java.lang.reflect.Method) on this instance of class com.learn.testcases.AddCustomerLoginTest due to class mismatch
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:75)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1243)
	at org.testng.internal.Invoker.createParameters(Invoker.java:992)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1082)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.learn.testcases.AddCustomerLoginTest@738dc9b]" name="tearDown" is-config="true" duration-ms="903" started-at="2019-11-11T16:20:04Z" finished-at="2019-11-11T16:20:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.learn.testcases.AddCustomerLoginTest -->
    </test> <!-- Add Customer Login Test -->
  </suite> <!-- Data Driven Basic -->
</testng-results>
